server:
  error:
    include-binding-errors: always
    include-message: always

spring:
  h2:
    console:
      enabled: 'true'
      username: sa
      path: /h2
  datasource:
    username: sa
    url: jdbc:h2:file:./dbFile
    password: ''
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql: trace
    org:
      springframework:
        security: DEBUG